services:
  - type: web
    name: eaglercraft-survival-free
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    numInstances: 1
    autoDeployTrigger: commit

    envVars:
      - key: PORT
        value: "10000"
      - key: SERVER_PORT
        value: "10000"
      - key: EULA
        value: "TRUE"
      - key: TYPE
        value: PAPER
      - key: VERSION
        value: "1.12.2"
      - key: PAPER_BUILD
        value: "1620"
      - key: PAPER_CHANNEL
        value: default
      - key: MEMORY
        value: 256M
      - key: INIT_MEMORY
        value: 128M
      - key: MAX_MEMORY
        value: 256M
      - key: JVM_OPTS
        value: "-XX:+UseSerialGC -XX:ActiveProcessorCount=1 -Xss192k -XX:MaxMetaspaceSize=96M -XX:MaxDirectMemorySize=48M -XX:ReservedCodeCacheSize=12M"
      - key: MALLOC_ARENA_MAX
        value: "1"
      - key: CLEAN_SERVER_LIBRARIES
        value: "false"
      - key: ONLINE_MODE
        value: "false"
      - key: ENABLE_RCON
        value: "false"
      - key: ENABLE_AUTOPAUSE
        value: "false"
      - key: ENABLE_AUTOSTOP
        value: "false"
      - key: USE_AIKAR_FLAGS
        value: "false"
      - key: MODE
        value: survival
      - key: DIFFICULTY
        value: normal
      - key: PVP
        value: "true"
      - key: MAX_PLAYERS
        value: "8"
      - key: VIEW_DISTANCE
        value: "4"
      - key: SPAWN_PROTECTION
        value: "0"
      - key: ALLOW_FLIGHT
        value: "true"
      - key: ENABLE_COMMAND_BLOCK
        value: "true"
      - key: MOTD
        value: "Eaglercraft Survival - Free Test"
      - key: PLUGINS
        value: |
          https://github.com/lax1dude/eaglerxserver/releases/download/v1.1.1/EaglerXServer.jar
          https://github.com/lenis0012/LoginSecurity/releases/download/v3.3.1/LoginSecurity-Spigot-3.3.1.jar
